version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal10
      MYSQL_USER: drupal10
      MYSQL_PASSWORD: drupal10
    ports:
      - "3307:3306"   # host:container -> use 3307 on Windows to avoid conflict with MySQL80
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"

volumes:
  db_data: