<?php

/**
 * @file
 * Contains rte_mis_gin.module.
 */

/**
 * Implements hook_page_attachments().
 */
function rte_mis_gin_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'rte_mis_gin/rte_mis_global';
  if (\Drupal::routeMatch()->getRouteName() == 'user.login') {
    $attachments['#attached']['library'][] = 'rte_mis_gin/rte_mis_login';
  }
  if (\Drupal::routeMatch()->getRouteName() == 'user.pass') {
    $attachments['#attached']['library'][] = 'rte_mis_gin/rte_mis_password';
  }
  if (\Drupal::routeMatch()->getRouteName() == 'user.register') {
    $attachments['#attached']['library'][] = 'rte_mis_gin/rte_mis_register';
  }
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function rte_mis_gin_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'page__custom';
}

/**
 * Implements hook_preprocess_page().
 */
function rte_mis_gin_preprocess_html(array &$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  switch ($route_name) {
    case 'user.login':
    case 'user.pass':
    case 'user.register':
      $variables['attributes']['class'][] = 'user-login--content';
      break;

    case 'entity.mini_node.canonical':
      $mini_node = \Drupal::routeMatch()->getParameter('mini_node');
      $bundle = $mini_node->bundle();
      if (in_array($bundle, ['school_details', 'student_details'])) {
        $variables['attributes']['class'][] = 'application-edit--view-wrapper';
      }
      break;
  }
}

/**
 * Implements hook_form_alter().
 */
function rte_mis_gin_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['anchor_link'] = [
      '#markup' => '<div class="forgot-pswrd-cta"><a href="/user/password">Forgot password?</a></div>',
    ];
  }
}

/**
 * Imeplements hook_theme_suggestions_block_alter().
 */
function rte_mis_gin_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (array_key_exists('#id', $variables['elements'])) {
    if ($variables['elements']['#id'] == 'gin_sitelogosection_2') {
      $suggestions[] = 'block__sitelogo';
    }

    if ($variables['elements']['#id'] == 'gin_mainmenu') {
      $suggestions[] = 'block__menu';
    }
  }
}

/**
 * Implements hook_theme().
 */
function rte_mis_gin_theme($existing, $type, $theme, $path) {
  return [
    'region__header' => [
      'base hook' => 'region',
      'template' => 'region--header',
    ],
    'region__rtebreadcrumb' => [
      'base hook' => 'region',
      'template' => 'region--rtebreadcrumb',
    ],
    'region__content' => [
      'base hook' => 'region',
      'template' => 'region--content',
    ],
    'page__custom' => [
      'base hook' => 'page',
      'template' => 'page--custom',
    ],
    'block__sitelogo' => [
      'base hook' => 'block',
      'template' => 'block--sitelogo',
    ],
    'block__menu' => [
      'base hook' => 'block',
      'template' => 'block--mainmenu',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function rte_mis_gin_theme_suggestions_region_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['#region'])) {
    $region = $variables['elements']['#region'];
    $suggestions[] = 'region__' . $region;

    if ($region == 'breadcrumb') {
      $suggestions[] = 'region__rtebreadcrumb';
    }
  }
}
