<?php

/**
 * @file
 * Contains rte_mis_gin.module.
 */

// libraries attached to differ pages

function rte_mis_gin_page_attachments(array &$attachments) {
  // Attach the library to all pages.
  $attachments['#attached']['library'][] = 'rte_mis_gin/rte_mis_global';
}

function rte_mis_gin_preprocess_page__user_login(&$variables) {
  // Implements hook_user_login().
  $variables['#attached']['library'][] = 'rte_mis_gin/rte_mis_login';
}

function rte_mis_gin_preprocess_page__user_password(&$variables) {
  // Implements hook_user_password().
  $variables['#attached']['library'][] = 'rte_mis_gin/rte_mis_password';
}

function rte_mis_gin_preprocess_page__user_register(&$variables) {
  // Implements hook_user_register().
  $variables['#attached']['library'][] = 'rte_mis_gin/rte_mis_register';
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function rte_mis_gin_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'page__custom';

  if (\Drupal::routeMatch()->getRouteName() == 'user.login') {
    $suggestions[] = 'page__user_login';
  }
  if (\Drupal::routeMatch()->getRouteName() == 'user.password') {
    $suggestions[] = 'page__user_password';
  }
  if (\Drupal::routeMatch()->getRouteName() == 'user.register') {
    $suggestions[] = 'page__user_register';
  }
}
function rte_mis_gin_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['anchor_link'] = array(
      '#markup' => '<div class="forgot-pswrd-cta"><a href="/user/password">Forgot password?</a></div>',
    );
  }
}

/**
 * Imeplements hook_theme_suggestions_block_alter().
 */
function rte_mis_gin_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if ($variables['elements']['#id'] == 'gin_sitelogosection_2') {
    $suggestions[] = 'block__sitelogo';
  }
  if ($variables['elements']['#id'] == 'gin_mainmenu') {
    $suggestions[] = 'block__menu';
  }
}

/**
 * Implements hook_theme().
 */
function rte_mis_gin_theme($existing, $type, $theme, $path) {
  return [
    'region__header' => [
      'base hook' => 'region',
      'template' => 'region--header',
    ],
    'region__rtebreadcrumb' => [
      'base hook' => 'region',
      'template' => 'region--rtebreadcrumb',
    ],
    'region__content' => [
      'base hook' => 'region',
      'template' => 'region--content',
    ],
    'page__custom' => [
      'base hook' => 'page',
      'template' => 'page--custom',
    ],
    'page__user_login' => [
      'base hook' => 'page',
      'template' => 'page--user-login',
    ],
    'page__user_password' => [
      'base hook' => 'page',
      'template' => 'page--user-password',
    ],
    'page__user_register' => [
      'base hook' => 'page',
      'template' => 'page--user-register',
    ],
    'block__sitelogo' => [
      'base hook' => 'block',
      'template' => 'block--sitelogo',
    ],
    'block__menu' => [
      'base hook' => 'block',
      'template' => 'block--mainmenu',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function rte_mis_gin_theme_suggestions_region_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['#region'])) {
    $region = $variables['elements']['#region'];
    $suggestions[] = 'region__' . $region;

    if ($region == 'breadcrumb') {
      $suggestions[] = 'region__' . 'rtebreadcrumb';
    }
  }
}
