<?php

/**
 * @file
 * Contains rte_mis_gin.module.
 */

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function rte_mis_gin_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'page__custom';

  if (\Drupal::routeMatch()->getRouteName() == 'user.login') {
    $suggestions[] = 'page__user_login';
  }
  if (\Drupal::routeMatch()->getRouteName() == 'user.password') {
    $suggestions[] = 'page__user_password';
  }
}
function rte_mis_gin_form_alter(&$form, &$form_state, $form_id) {
  // Check if the form ID matches the user login form.
  if ($form_id == 'user_login_form') {
    // Add anchor tag to the form.
    $form['anchor_link'] = array(
      '#markup' => '<div class="forgot-pswrd-cta"><a href="/user/password">Forgot password?</a></div>',
    );
  }
}
// function rte_mis_gin_theme_suggestions_form_alter(array &$suggestions, array $variables) {
//   // Add a suggestion for the user-login form.
//   if ($variables['element']['#form_id'] == 'user_login_form') {
//     $suggestions[] = 'form__user_login';
//   }
// }

/**
 * Imeplements hook_theme_suggestions_block_alter().
 */
function rte_mis_gin_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if ($variables['elements']['#id'] == 'gin_sitelogosection_2') {
    $suggestions[] = 'block__sitelogo';
  }
  if ($variables['elements']['#id'] == 'gin_mainmenu') {
    $suggestions[] = 'block__menu';
  }
}

/**
 * Implements hook_theme().
 */
function rte_mis_gin_theme($existing, $type, $theme, $path) {
  return [
    'region__header' => [
      'base hook' => 'region',
      'template' => 'region--header',
    ],
    'region__rtebreadcrumb' => [
      'base hook' => 'region',
      'template' => 'region--rtebreadcrumb',
    ],
    'region__content' => [
      'base hook' => 'region',
      'template' => 'region--content',
    ],
    'page__custom' => [
      'base hook' => 'page',
      'template' => 'page--custom',
    ],
    'page__user_login' => [
      'base hook' => 'page',
      'template' => 'page--user-login',
    ],
    'page__user_password' => [
      'base hook' => 'page',
      'template' => 'page--user-password',
    ],
    'block__sitelogo' => [
      'base hook' => 'block',
      'template' => 'block--sitelogo',
    ],
    'block__menu' => [
      'base hook' => 'block',
      'template' => 'block--mainmenu',
    ],
    // 'form__user_login' => [
    //   'render element' => 'form',
    //   'template' => 'form--user-login',
    // ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function rte_mis_gin_page_attachments(array &$attachments) {
  // Attach the library to all pages.
  $attachments['#attached']['library'][] = 'rte_mis_gin/rte_mis_global';
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function rte_mis_gin_theme_suggestions_region_alter(array &$suggestions, array $variables) {

  // Check if the 'region' variable is set within 'elements'.
  if (isset($variables['elements']['#region'])) {
    // Get the region name.
    $region = $variables['elements']['#region'];

    // Add a theme hook suggestion based on the region name.
    $suggestions[] = 'region__' . $region;

    if ($region == 'breadcrumb') {
      $suggestions[] = 'region__' . 'rtebreadcrumb';
    }
  }
}
