# Schema for the configuration files of the rte_mis_home module.
rte_mis_home.settings:
  type: config_object
  label: 'rte_mis_home settings'
  mapping:
    banner_image:
      type: string
      label: 'Banner Image'

block.settings.rte_mis_home_two_column_block:
  type: block_settings
  label: 'Two Column Block block'
  mapping:
    image:
      type: string
      label: 'Image path'
    title:
      type: string
      label: 'Title'
    description:
      type: string
      label: 'Description'
    link:
      type: string
      label: 'Link URL'
