# Schema for the configuration files of the rte_mis_home module.
rte_mis_home.settings:
  type: config_object
  label: 'rte_mis_home settings'
  mapping:
    banner_image:
      type: string
      label: 'Banner Image'
