<?php

/**
 * @file
 * Contains rte_mis_school.module.
 */

use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\eck\EckEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\taxonomy\Entity\Term;
use Drupal\taxonomy\TermInterface;
use Drupal\user\Entity\User;
use Drupal\user\UserInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function rte_mis_school_user_presave(UserInterface $user) {
  // Check the user role and based on that define what should be the user name
  // of the user.
  $roles = $user->getRoles();
  if (!empty($roles)) {
    // Now add the check for different roles.
    if ((count($roles) === 1 & in_array('anonymous', $roles))
      || (in_array('school_admin', $roles))) {
      // If user is having only anonymous user role or if the user is having
      // school admin role, then the user name should be the school UDISE code.
      $target_id = $user->get('field_school_details')->getString();
      if (!empty($target_id)) {
        $school_details = \Drupal::entityTypeManager()->getStorage('mini_node')->load($target_id);
        if ($school_details instanceof EckEntityInterface) {
          $term_target_id = $school_details->get('field_udise_code')->getString();
          // Load the UDISE code term.
          $udise_term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($term_target_id);
          if ($udise_term instanceof TermInterface) {
            $udise_code = $udise_term->getName();
            if (!empty($udise_code)) {
              // Set the UDISE code as username for school user.
              $user->setUsername($udise_code);
            }
          }
        }
      }
    }
    elseif (in_array('block_admin', $roles)) {
      // Generate a username for block admin user based on the block.
      // @todo Add the logic to generate block username.
    }
    elseif (in_array('state_admin', $roles)) {
      // @todo Add the logic to generate state username.
    }
    elseif (in_array('district_admin', $roles)) {
      // @todo Add the logic to generate district username.
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rte_mis_school_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['name']['#title'] = t('Username or UDISE Code');
}

/**
 * Implements hook_form_alter().
 */
function rte_mis_school_form_alter(&$form, FormStateInterface $form_state, string $form_id) {
  if ($form_id === 'user_form') {
    // Show username in readonly format.
    $form['account']['name']['#access'] = TRUE;
    $form['account']['name']['#attributes']['readonly'] = 'readonly';
    $form['account']['name']['#attributes']['disabled'] = 'disabled';
  }
  elseif ($form_id === 'user_register') {
    $form['account']['name']['#access'] = FALSE;
  }
  elseif ($form_id === 'user_register_form') {
    $form['#validate'][] = '_rte_mis_school_udise_validation';
  }
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function rte_mis_school_inline_entity_form_entity_form_alter(&$form, FormStateInterface $form_state) {
  // Validate if the field exists or not in the form before doing any changes.
  if (array_key_exists('field_school_name', $form)) {
    $form['field_school_name']['widget'][0]['value']['#attributes']['readonly'] = 'readonly';
  }

  if (array_key_exists('field_udise_code', $form)) {
    $form['#prefix'] = '<div id="form-ajax-wrapper">';
    $form['#suffix'] = '</div>';

    $form['field_udise_code']['widget']['#ajax'] = [
      'callback' => 'rte_mis_school_populate_school_name',
      'wrapper' => 'form-ajax-wrapper',
      'event' => 'select2:select',
      'method' => 'replace',
      'progress' => [
        'type' => 'throbber',
        'message' => t('Searching School Name...'),
      ],
    ];

    // Add the udise code cache tag so that we get the updated list of UDISE
    // code everytime any changes occurs in the vocab.
    $form['#cache']['tags'] = array_merge($form['#cache']['tags'] ?? [], ['taxonomy_term_list:school_udise_code']);
  }
}

/**
 * Callback function to populate the school name based on UDISE code.
 */
function rte_mis_school_populate_school_name(array $form, FormStateInterface $form_state) {
  // @todo Need to add proper validations here.
  // Get the UDISE code term value.
  $target_id = $form_state->getValue('field_school_details')[0]['inline_entity_form']['field_udise_code'];

  if (!empty($target_id) && $target_id[0]['value'] !== '_none') {
    // Load the term and get the School name.
    $term = Term::load($target_id[0]['value']);
    $school_name = $term->get('field_school_name')->getString();
    $form['field_school_details']['widget'][0]['inline_entity_form']['field_school_name']['widget'][0]['value']['#value'] = $school_name;
  }
  else {
    $form['field_school_details']['widget'][0]['inline_entity_form']['field_school_name']['widget'][0]['value']['#value'] = '';
  }

  return $form['field_school_details']['widget'][0]['inline_entity_form'];
}

/**
 * Callback function to provide the list of approved UDISE code.
 */
function rte_mis_school_udise_list(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  // Load all the approved UDISE terms.
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
    'vid' => 'school_udise_code',
    'field_workflow' => 'school_udise_code_workflow_approved',
  ]);

  $options = [
    '_none' => '- None -',
  ];
  foreach ($terms as $term) {
    if ($term instanceof Term) {
      $options[$term->id()] = $term->label();
    }
  }

  return $options;
}

/**
 * Callback function to provide the list of multiple fields.
 */
function rte_mis_school_default_field_options(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = TRUE) {
  $options = [];
  // Get the field name.
  $field_name = $definition->getName();
  $config = \Drupal::config('rte_mis_school.settings')->get('field_default_options');
  if (in_array($field_name, [
    'field_aid_status',
    'field_minority_status',
    'field_medium',
    'field_education_type',
    'field_board_type',
    'field_education_level',
  ])) {
    // Get the field name with option defined.
    $defined_options = $config[$field_name] ?? NULL;
    if (isset($defined_options)) {
      $options = $defined_options;
    }
  }
  elseif (in_array($field_name, [
    'field_education_level_from',
    'field_education_level_to',
  ])) {
    $options = $config['class_level'];
  }
  return $options;

}

/**
 * Implements hook_local_tasks_alter().
 */
function rte_mis_school_local_tasks_alter(&$local_tasks) {
  // Alter the destination query parameter for delete local task in taxonomy.
  if ($local_tasks['entity.taxonomy_term.delete_form']) {
    $local_tasks['entity.taxonomy_term.delete_form']['class'] = '\Drupal\rte_mis_school\Plugin\Menu\AlterTaxonomyLocalTask';
  }
}

/**
 * Callback function to check if School exists with the same UDISE code.
 */
function _rte_mis_school_udise_validation(&$form, FormStateInterface $form_state) {
  // Validate this only when the submit button is triggered.
  $triggered_element = $form_state->getTriggeringElement();
  if ($triggered_element['#name'] === 'op') {
    $school_details = $form_state->getValue('field_school_details');
    if (!empty($school_details)) {
      $target_id = $school_details[0]['inline_entity_form']['field_udise_code'][0]['value'];
      $school_info = \Drupal::entityTypeManager()->getStorage('mini_node')->loadByProperties([
        'field_udise_code' => $target_id,
      ]);
      if (count($school_info) > 0) {
        // Reset the school info array.
        $school_info = array_pop($school_info);
        if ($school_info instanceof EckEntityInterface) {
          // Throw error for the UDISE code.
          $form_state->setErrorByName('field_school_details', t('Account already exists with this UDISE Code.'));
        }
      }
    }
  }
}

/**
 * Implements hook_views_pre_build().
 */
function rte_mis_school_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  // Pass the argument for contextual filter for user info view.
  if ($view->id() == 'school_basic_information' && $display_id == 'school_info') {
    // Get the udise code information from the current logged in user.
    $user = User::load(\Drupal::currentUser()->id());
    if ($user instanceof UserInterface) {
      $school_target_id = $user->get('field_school_details')->getString();
      if (!empty($school_target_id)) {
        // @todo Move the below code in a helper service because the code is
        // getting used at multiple places.
        $school_details = \Drupal::entityTypeManager()->getStorage('mini_node')->load($school_target_id);
        if ($school_details instanceof EckEntityInterface) {
          $term_target_id = $school_details->get('field_udise_code')->getString();
          // Load the UDISE code term.
          $udise_term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($term_target_id);
          if ($udise_term instanceof TermInterface) {
            $udise_code = $udise_term->getName();
            if (!empty($udise_code)) {
              $args[0] = $udise_code;
            }
          }
        }
      }
    }
  }
}

/**
 * Ajax callback for populating option of education level paragraph.
 */
function rte_mis_school_education_level_wrapper_callback(&$form, FormStateInterface $form_state) {
  // Get the triggering element.
  $triggering_element = $form_state->getTriggeringElement();
  // Get the parent based to return as ajax wrapper.
  $element = NestedArray::getValue($form, array_slice($triggering_element['#array_parents'], 0, 1));
  // Load the config, to get the options.
  $default_option = \Drupal::config('rte_mis_school.settings')->get('field_default_options') ?? [];
  // Get the children i.e. the multiple paragraph created.
  $children = Element::children($element['widget'], TRUE);
  $values = $form_state->getValues();
  foreach ($children as $child) {
    // Only process the numeric children.
    if (is_numeric($child)) {
      // Get the current row values.
      $current_row_value = $values['field_education_details'][$child]['subform'] ?? [];
      // Get the current value from the fields.
      $current_education_level = isset($triggering_element['#field_name']) ? $current_row_value['field_education_level'][0]['value'] ?? NULL : $current_row_value['field_education_level'] ?? NULL;
      $current_education_level_from = isset($triggering_element['#field_name']) ? $current_row_value['field_education_level_from'][0]['value'] ?? NULL : $current_row_value['field_education_level_from'] ?? NULL;
      $current_education_level_to = isset($triggering_element['#field_name']) ? $current_row_value['field_education_level_to'][0]['value'] ?? NULL : $current_row_value['field_education_level_to'] ?? NULL;
      // Get the options to be displayed to select list.
      $config_option_education_level_from = $current_education_level ? $default_option['field_education_level_from'][$current_education_level] ?? [] : [];
      $config_option_education_level_to = $current_education_level ? $default_option['field_education_level_to'][$current_education_level] ?? [] : [];
      // Prepare the option for field_education_level_from field.
      $education_level_from_options = rte_mis_school_get_education_level_options($config_option_education_level_from['from'] ?? NULL, $config_option_education_level_from['to'] ?? NULL);
      $element['widget'][$child]['subform']['field_education_level_from']['widget']['#options'] = $education_level_from_options;
      $element['widget'][$child]['subform']['field_education_level_from']['widget']['#default_value'] = $current_education_level_from;
      // Prepare the option for field_education_level_to field.
      $education_level_to_options = rte_mis_school_get_education_level_options($config_option_education_level_to['from'] ?? NULL, $config_option_education_level_to['to'] ?? NULL);
      $element['widget'][$child]['subform']['field_education_level_to']['widget']['#options'] = $education_level_to_options;
      $element['widget'][$child]['subform']['field_education_level_to']['widget']['#default_value'] = $current_education_level_to;
    }
  }
  return $element;
}

/**
 * Get the option for education level field.
 *
 * @param mixed $start
 *   Start position of option.
 * @param mixed $end
 *   End position of option.
 */
function rte_mis_school_get_education_level_options($start = NULL, $end = NULL) {
  // Get the class level options.
  $class_levels = \Drupal::config('rte_mis_school.settings')->get('field_default_options.class_level') ?? [];
  // Initialize the array with all the options.
  $options = $class_levels;

  // Slice the array based on start and end position.
  if (is_numeric($start) && is_numeric($end)) {
    $options = array_slice($class_levels, $start, (($end - $start) + 1), TRUE) ?? [];
  }

  return $options;
}

/**
 * Implements hook_field_widget_complete_WIDGET_TYPE_form_alter().
 */
function rte_mis_school_field_widget_complete_paragraphs_table_widget_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  if ($context['items']->getName() == 'field_education_details') {
    $field_widget_complete_form['#attributes']['id'][] = 'education-level-wrapper';
    // Ajax should called on add more item.
    $field_widget_complete_form['widget']['add_more']['add_more_button_education_level']['#ajax']['callback'] = 'rte_mis_school_education_level_wrapper_callback';
    // Add validation for education level paragraph.
    $field_widget_complete_form['widget']['#element_validate'][] = 'rte_mis_school_validate_education_level_paragraph';
  }
}

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
function rte_mis_school_field_widget_single_element_paragraphs_table_widget_form_alter(array &$element, FormStateInterface $form_state, array $context) {
  if ($element['#paragraph_type'] == 'education_level') {
    // Add ajax property in field_education_level field.
    $element['subform']['field_education_level']['widget']['#ajax'] = [
      'callback' => 'rte_mis_school_education_level_wrapper_callback',
      'wrapper' => 'education-level-wrapper',
    ];
  }
}

/**
 * Validate the `education_level` paragraph.
 */
function rte_mis_school_validate_education_level_paragraph(&$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  $education_details = $values['field_education_details'] ?? [];
  foreach ($education_details as $key => $value) {
    if (is_numeric($key)) {
      $education_level_from = $value['subform']['field_education_level_from'][0]['value'] ?? NULL;
      $education_level_to = $value['subform']['field_education_level_to'][0]['value'] ?? NULL;
      if ($education_level_from > $education_level_to) {
        $form_state->setError($form[$key]['subform']['field_education_level_from']['widget'], t('Please select proper education level.'));
      }
    }
  }
}
