rte_mis_core.settings:
  type: config_object
  label: 'RTE MIS Core Settings'
  mapping:
    location_schema:
      type: mapping
      label: 'Location Settings'
      mapping:
        enable:
          type: boolean
          label: 'Categories location into Rural/Urban'
        rural:
          type: integer
          label: 'Select schema that should marked as Rural while creating location'
        urban:
          type: integer
          label: 'Select schema that should marked as Urban while creating location'
        depth:
          type: integer
          label: 'Stores the depth for categorization(U/R) in location schema vocabulary'
    entry_class:
      type: mapping
      label: 'Entry Class Settings'
      mapping:
        class_type:
          type: string
          label: 'Entry class type ( Single or Dual )'

