# Schema for the configuration files of the rte_mis_school module.

# Schema for textfield_to_integer field widget.
field.widget.settings.textfield_to_integer:
  type: mapping
  label: 'Integer Textfield widget settings'
  mapping:
    label:
      type: label
      label: 'Title'
    placeholder:
      type: label
      label: 'Placeholder'
# Schema for rte_mis_school.settings
rte_mis_school.settings:
  type: config_object
  label: 'RTE MIS School Settings'
  mapping:
    school_verification:
      type: mapping
      label: 'School Verification'
      mapping:
        single_approval:
          type: boolean
          label: 'Enable single approval process'
        single_approval_role:
          type: string
          label: 'Select Role'
