<?php

/**
 * @file
 * Primary module hooks for rte_mis_home module.
 */

/**
 * Implements hook_theme().
 */
function rte_mis_home_theme($existing, $type, $theme, $path) {
  return [
    'statistics_block' => [
      'variables' => [
        'statistics' => [],
      ],
      'template' => 'statistics-block',
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function rte_mis_home_preprocess_page(array &$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  switch ($route_name) {
    case 'view.frontpage.page_1':
      // Load the configuration.
      $config = \Drupal::config('rte_mis_home.settings');
      $banner_image_fids = $config->get('banner_images');

      // Initialize an array to hold the banner image URLs.
      $banner_image_urls = [];

      // Load the file entities and generate their URLs.
      if (!empty($banner_image_fids)) {
        foreach ($banner_image_fids as $fid) {
          $file = \Drupal::entityTypeManager()->getStorage('file')->load($fid);
          if ($file) {
            $banner_image_urls[] = \Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
          }
        }
      }

      // Pass the banner image URLs to the template variables.
      $variables['banner_image_urls'] = $banner_image_urls;

      // Add the total_allotment variable.
      $variables['total_allotment'] = [
        'total' => 1234,
        'year_range' => '2024 - 2025',
        'text' => 'Total Allotment',
      ];
      break;
  }
}
