<?php

/**
 * @file
 * Primary module hooks for rte_mis_home module.
 */

/**
 * Implements hook_theme().
 */
function rte_mis_home_theme($existing, $type, $theme, $path) {
  return [
    'statistics_block' => [
      'variables' => [
        'statistics' => [],
      ],
      'template' => 'statistics-block',
    ],
    'eligibility_criteria' => [
      'variables' => [
        'class_ages' => [],
        'categories' => [],
        'others' => [],
      ],
      'template' => 'eligibility-criteria',
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function rte_mis_home_preprocess_page(array &$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  switch ($route_name) {
    case 'view.frontpage.page_1':
      // Load the configuration.
      $config = \Drupal::config('rte_mis_home.settings');
      $banner_image_fid = $config->get('banner_image');

      // Initialize the banner image URL.
      $banner_image_url = NULL;

      // Load the file entity and generate its URL.
      if (!empty($banner_image_fid)) {
        $file = \Drupal::entityTypeManager()->getStorage('file')->load($banner_image_fid);
        if ($file) {
          $banner_image_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
        }
      }

      // Pass the banner image URL to the template variables.
      $variables['banner_image_url'] = $banner_image_url;

      // Add the total_allotment variable.
      $variables['total_allotment'] = [
        'total' => 1234,
        'year_range' => '2024 - 2025',
        'text' => 'Total Allotment',
      ];
      break;
  }
}
