name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - master
trigger:
  branches:
    include:
      - master

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-lively-beach-0da1edd03-variable-group
  - name: node_version
    value: 22.14.0
  steps:
  - checkout: self
    submodules: true

  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: Install Node.js

  - script: npm ci
    displayName: Install dependencies

  - script: npm run build-storybook
    displayName: Build Storybook

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BEACH_0DA1EDD03)
      app_location: "storybook-static"
      output_location: ""
      skip_app_build: true

